apiVersion: batch/v1
kind: Job
metadata:
  name: nngpt-postproc-test
  namespace: b-s-mulukuledu
spec:
  backoffLimit: 0
  template:
    metadata:
      annotations:
        lemur/conda-env: ve
        lemur/image: pytorch
    spec:
      restartPolicy: Never
      securityContext:
        runAsUser: 1025
        runAsGroup: 1376
        fsGroup: 1376
      containers:
      - name: nngpt
        image: ws.ab/shared/ai-linux-nngpt:v1
        workingDir: /a/mm
        command: ["python3", "-u", "/a/mm/run.py", "ab.gpt.TuneNNGen"]
        args:
        - "--llm_conf"
        - "ds_coder_7b_olympic.json"
        - "--num_train_epochs"
        - "1"
        - "--test_nn"
        - "20"
        - "--learning_rate"
        - "5e-6"
        env:
        - name: HOME
          value: /home/ab
        - name: PYTORCH_CUDA_ALLOC_CONF
          value: "expandable_segments:True"
        - name: PYTORCH_ALLOC_CONF
          value: "expandable_segments:True"
        resources:
          requests:
            nvidia.com/gpu: "1"
            cpu: "8"
            memory: "30Gi"
          limits:
            nvidia.com/gpu: "1"
            cpu: "64"
            memory: "120Gi"
        volumeMounts:
        - name: v0
          mountPath: /a/mm
        - name: v1
          mountPath: /a/mm/data
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: v0
        hostPath:
          path: /shared/ssd/home/b-s-mulukuledu/exp
      - name: v1
        hostPath:
          path: /shared/local/data/a-group-automl/data
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 16Gi
